name: "🚀 Enhancement"
description: "Use this template to describe an Enhancement of MEmilio"
labels:
  - "class::improvement"
body:
- type: markdown
  attributes:
    value: "Please check our [existing issues](https://github.com/DLR-SC/memilio/issues) beforehand."
- type: textarea
  id: motivation
  attributes:
    label: "Motivation / Current Behaviour"
    description: "Describe the motivation / current behaviour."
- type: textarea
  id: enhancement-description
  attributes:
    label: "Enhancement description"
    description: "Describe the enhancement."
  validations:
    required: true
- type: textarea
  id: -context
  attributes:
    label: "Additional context"
    description: "Code location/examples, Papers, Mathematics, put them here."
- type: checkboxes
  id: checks
  attributes:
    label: Checklist
    description: Add Labels and add this issue to a project.
    options:
      - label: "Attached labels, especially loc:: or model:: labels."
        required: false
      - label: Linked to project
        required: false
