name: CI

on:
  schedule:
    - cron: "40 2 * * *"
  push:
    branches:
      - "main"
    tags:
      - version-*
    paths-ignore:
      - "**/memilio-epidata/**"
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    paths-ignore:
      - "**/memilio-epidata/**"
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.0

  build-cpp-gcc_clang:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        compiler: ["gcc", "clang"]
        config: ["Debug", "Release"]
        version: ["latest", "min"]
        include:
          - version: "latest"
            os: "ubuntu-latest"
          - version: "min"
            os: "ubuntu-20.04"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-build
        with:
          compiler: ${{ matrix.compiler }}
          config: ${{ matrix.config }}
          version: ${{ matrix.version }}
          coverage: ${{ (matrix.compiler == 'gcc' && matrix.config == 'Debug' && matrix.version == 'latest') && 'ON' || 'OFF' }} # `c && t || f` is (usually) equivalent to `c ? t : f`
          sanitize-addr: ${{ (matrix.compiler == 'gcc' && matrix.config == 'Debug' && matrix.version == 'latest') && 'ON' || 'OFF' }}
          sanitize-ub: ${{ (matrix.compiler == 'gcc' && matrix.config == 'Debug' && matrix.version == 'latest') && 'ON' || 'OFF' }}

  build-cpp-gcc-no-optional-deps:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-build
        with:
          compiler: gcc
          version: latest
          config: Release
          optional-dependencies: OFF

  build-cpp-msvc:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        config: ["Debug", "Release"]
        version: ["latest", "min"]
        include:
          - version: "latest"
            os: "windows-2022"
          - version: "min"
            os: "windows-2019"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-build
        with:
          config: ${{ matrix.config }}
          version: ${{ matrix.version }}

  build-cpp-msvc-no-optional-deps:
    if: github.event.pull_request.draft == false
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-build
        with:
          config: Release
          version: latest
          optional-dependencies: OFF

  test-cpp-gcc_clang:
    if: github.event.pull_request.draft == false
    needs: build-cpp-gcc_clang
    strategy:
      matrix:
        compiler: ["gcc", "clang"]
        config: ["Debug", "Release"]
        version: ["latest", "min"]
        include:
          - version: "latest"
            os: "ubuntu-latest"
          - version: "min"
            os: "ubuntu-20.04"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-test
        with:
          build-artifact: build-cpp-linux-${{ matrix.compiler }}-${{ matrix.version }}-${{ matrix.config }}-full
          coverage: ${{ (matrix.compiler == 'gcc' && matrix.version == 'latest' && matrix.config == 'Debug') && 'ON' || 'OFF' }}

  test-linux-no-optional-deps:
    if: github.event.pull_request.draft == false
    needs: build-cpp-gcc-no-optional-deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-test
        with:
          build-artifact: build-cpp-linux-gcc-latest-Release-part

  test-cpp-msvc:
    if: github.event.pull_request.draft == false
    needs: build-cpp-msvc
    strategy:
      matrix:
        config: ["Debug", "Release"]
        version: ["latest", "min"]
        include:
          - version: "latest"
            os: "windows-2022"
          - version: "min"
            os: "windows-2019"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-test
        with:
          build-artifact: build-cpp-windows-msvc-${{ matrix.version }}-${{ matrix.config }}-full

  test-windows-no-optional-deps:
    if: github.event.pull_request.draft == false
    needs: build-cpp-msvc-no-optional-deps
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-test
        with:
          build-artifact: build-cpp-windows-msvc-latest-Release-part

  run_examples-cpp-gcc_clang:
    if: github.event.pull_request.draft == false
    needs: build-cpp-gcc_clang
    strategy:
      matrix:
        compiler: ["gcc", "clang"]
        config: ["Debug", "Release"]
        version: ["latest", "min"]
        include:
          - version: "latest"
            os: "ubuntu-latest"
          - version: "min"
            os: "ubuntu-20.04"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/linux-run_examples
        with:
          build-artifact: build-cpp-linux-${{ matrix.compiler }}-${{ matrix.version }}-${{ matrix.config }}-full

  run_examples-cpp-msvc:
    if: github.event.pull_request.draft == false
    needs: build-cpp-msvc
    strategy:
      matrix:
        config: ["Debug", "Release"]
        version: ["latest", "min"]
        include:
          - version: "latest"
            os: "windows-2022"
          - version: "min"
            os: "windows-2019"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/windows-run_examples
        with:
          build-artifact: build-cpp-windows-msvc-${{ matrix.version }}-${{ matrix.config }}-full

  build-py-generation:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-py
        with:
          package: generation

  build-py-simulation:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-py
        with:
          package: simulation

  build-py-surrogatemodel:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build-py
        with:
          package: surrogatemodel

  test-py-generation:
    if: github.event.pull_request.draft == false
    strategy:
      matrix: 
        version: ["3.8", "3.11"]
    needs: build-py-generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-py
        with:
          package: generation

  test-py-simulation:
    if: github.event.pull_request.draft == false
    needs: build-py-simulation
    strategy:
      matrix: 
        version: ["3.8", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-py
        with:
          package: simulation

  test-py-surrogatemodel:
    if: github.event.pull_request.draft == false
    needs: [build-py-surrogatemodel, build-py-simulation]
    strategy:
      matrix: 
        version: ["3.8", "3.11"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-py
        with:
          package: surrogatemodel
          coverage: ON

  test-docs:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test-docs

  codecov:
    if: github.event.pull_request.draft == false
    needs: [test-cpp-gcc_clang, test-py-surrogatemodel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq -y install git curl
      - name: Download python coverage report
        uses: actions/download-artifact@v3
        with:
          name: test-py-coverage-reports-surrogatemodel
      - name: Download cpp coverage report
        uses: actions/download-artifact@v3
        with:
          name: test-cpp-coverage-reports
      - name: Deploy to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage_python
          files: ./coverage_python/**,./coverage.info
          verbose: true

  pages:
    if: github.event.pull_request.draft == false
    needs: [test-cpp-gcc_clang, test-docs, test-py-surrogatemodel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq -y install git
      - name: Download python coverage report
        uses: actions/download-artifact@v3
        with:
          name: test-py-coverage-reports-surrogatemodel
      - name: Download cpp coverage report
        uses: actions/download-artifact@v3
        with:
          name: test-cpp-coverage-reports
      - name: Download documentation
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: docs/html
      - name: Prepare basic Pages sites
        run: |
          mkdir -p public
          cp docs/style.css public/style.css
          cp docs/index.html public/index.html
      - name: Prepare documentation
        run: |
          mkdir -p public/documentation
          cp -r docs/html/* public/documentation
      - name: Prepare coverage reports
        run: |
          mkdir -p public/coverage
          mkdir -p public/coverage/cpp
          mkdir -p public/coverage/python
          cp -r coverage_python/* public/coverage/python/
          cp -r coverage/* public/coverage/cpp/
      - name: Upload pages as artifact
        uses: actions/upload-artifact@v3
        if: github.event_name == 'pull_request' && github.ref != 'refs/heads/main'
        with:
          name: pages
          path: public
          if-no-files-found: error
          retention-days: 1
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
